spring:
  profiles:
      active:
        - dev
  application:
    name: newspaper
  datasource:
    username: username
    password: password
    driver-class-name: driver-class-name
    url: url
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    database-platform: database-platform

