spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:newspaper
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

