spring:
  application:
    name: newspaper-app
  profiles:
    active:
      - dev
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      uri: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    database-platform: database-platform
server:
  port: 2000
app:
  cache:
    maxSize: 3
    algorithm: LRU