version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newspaper
    ports:
      - '5555:5432'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512m
    networks:
      - docker-network
  newspaper-app:
    ports:
      - '1000:2000'
    build:
      dockerfile: newspaper-app/Dockerfile
      context: ..
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/newspaper
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512m
    networks:
      - docker-network
  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge